receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheusremotewrite:
    endpoint: "http://victoriametrics:8428/api/v1/write"
  jaeger:
    endpoint: "jaeger-all-in-one:14250"
    tls:
      insecure: true

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

extensions:
  health_check:
  pprof:
    endpoint: ":1888"
  zpages:
    endpoint: ":55679"

service:
  extensions: [ pprof, zpages, health_check ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ jaeger ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheusremotewrite ]
