// Code generated by Kitex v0.12.1. DO NOT EDIT.

package relationservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	relation "simpledouyin/kitex_gen/douyin/relation"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Follow": kitex.NewMethodInfo(
		followHandler,
		newFollowArgs,
		newFollowResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Unfollow": kitex.NewMethodInfo(
		unfollowHandler,
		newUnfollowArgs,
		newUnfollowResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetFollowList": kitex.NewMethodInfo(
		getFollowListHandler,
		newGetFollowListArgs,
		newGetFollowListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CountFollowList": kitex.NewMethodInfo(
		countFollowListHandler,
		newCountFollowListArgs,
		newCountFollowListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetFollowerList": kitex.NewMethodInfo(
		getFollowerListHandler,
		newGetFollowerListArgs,
		newGetFollowerListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CountFollowerList": kitex.NewMethodInfo(
		countFollowerListHandler,
		newCountFollowerListArgs,
		newCountFollowerListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetFriendList": kitex.NewMethodInfo(
		getFriendListHandler,
		newGetFriendListArgs,
		newGetFriendListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"IsFollow": kitex.NewMethodInfo(
		isFollowHandler,
		newIsFollowArgs,
		newIsFollowResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	relationServiceServiceInfo                = NewServiceInfo()
	relationServiceServiceInfoForClient       = NewServiceInfoForClient()
	relationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return relationServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return relationServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return relationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RelationService"
	handlerType := (*relation.RelationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "simpledouyin.user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.1",
		Extra:           extra,
	}
	return svcInfo
}

func followHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(relation.RelationActionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(relation.RelationService).Follow(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FollowArgs:
		success, err := handler.(relation.RelationService).Follow(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FollowResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFollowArgs() interface{} {
	return &FollowArgs{}
}

func newFollowResult() interface{} {
	return &FollowResult{}
}

type FollowArgs struct {
	Req *relation.RelationActionRequest
}

func (p *FollowArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(relation.RelationActionRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *FollowArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *FollowArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *FollowArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FollowArgs) Unmarshal(in []byte) error {
	msg := new(relation.RelationActionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FollowArgs_Req_DEFAULT *relation.RelationActionRequest

func (p *FollowArgs) GetReq() *relation.RelationActionRequest {
	if !p.IsSetReq() {
		return FollowArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FollowArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FollowArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FollowResult struct {
	Success *relation.RelationActionResponse
}

var FollowResult_Success_DEFAULT *relation.RelationActionResponse

func (p *FollowResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(relation.RelationActionResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *FollowResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *FollowResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *FollowResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FollowResult) Unmarshal(in []byte) error {
	msg := new(relation.RelationActionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FollowResult) GetSuccess() *relation.RelationActionResponse {
	if !p.IsSetSuccess() {
		return FollowResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FollowResult) SetSuccess(x interface{}) {
	p.Success = x.(*relation.RelationActionResponse)
}

func (p *FollowResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FollowResult) GetResult() interface{} {
	return p.Success
}

func unfollowHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(relation.RelationActionRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(relation.RelationService).Unfollow(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnfollowArgs:
		success, err := handler.(relation.RelationService).Unfollow(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnfollowResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnfollowArgs() interface{} {
	return &UnfollowArgs{}
}

func newUnfollowResult() interface{} {
	return &UnfollowResult{}
}

type UnfollowArgs struct {
	Req *relation.RelationActionRequest
}

func (p *UnfollowArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(relation.RelationActionRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *UnfollowArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *UnfollowArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *UnfollowArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnfollowArgs) Unmarshal(in []byte) error {
	msg := new(relation.RelationActionRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnfollowArgs_Req_DEFAULT *relation.RelationActionRequest

func (p *UnfollowArgs) GetReq() *relation.RelationActionRequest {
	if !p.IsSetReq() {
		return UnfollowArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnfollowArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnfollowArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnfollowResult struct {
	Success *relation.RelationActionResponse
}

var UnfollowResult_Success_DEFAULT *relation.RelationActionResponse

func (p *UnfollowResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(relation.RelationActionResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *UnfollowResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *UnfollowResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *UnfollowResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnfollowResult) Unmarshal(in []byte) error {
	msg := new(relation.RelationActionResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnfollowResult) GetSuccess() *relation.RelationActionResponse {
	if !p.IsSetSuccess() {
		return UnfollowResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnfollowResult) SetSuccess(x interface{}) {
	p.Success = x.(*relation.RelationActionResponse)
}

func (p *UnfollowResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnfollowResult) GetResult() interface{} {
	return p.Success
}

func getFollowListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(relation.FollowListRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(relation.RelationService).GetFollowList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetFollowListArgs:
		success, err := handler.(relation.RelationService).GetFollowList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetFollowListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetFollowListArgs() interface{} {
	return &GetFollowListArgs{}
}

func newGetFollowListResult() interface{} {
	return &GetFollowListResult{}
}

type GetFollowListArgs struct {
	Req *relation.FollowListRequest
}

func (p *GetFollowListArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(relation.FollowListRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetFollowListArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetFollowListArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetFollowListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetFollowListArgs) Unmarshal(in []byte) error {
	msg := new(relation.FollowListRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetFollowListArgs_Req_DEFAULT *relation.FollowListRequest

func (p *GetFollowListArgs) GetReq() *relation.FollowListRequest {
	if !p.IsSetReq() {
		return GetFollowListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetFollowListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetFollowListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetFollowListResult struct {
	Success *relation.FollowListResponse
}

var GetFollowListResult_Success_DEFAULT *relation.FollowListResponse

func (p *GetFollowListResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(relation.FollowListResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetFollowListResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetFollowListResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetFollowListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetFollowListResult) Unmarshal(in []byte) error {
	msg := new(relation.FollowListResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetFollowListResult) GetSuccess() *relation.FollowListResponse {
	if !p.IsSetSuccess() {
		return GetFollowListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetFollowListResult) SetSuccess(x interface{}) {
	p.Success = x.(*relation.FollowListResponse)
}

func (p *GetFollowListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetFollowListResult) GetResult() interface{} {
	return p.Success
}

func countFollowListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(relation.CountFollowListRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(relation.RelationService).CountFollowList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CountFollowListArgs:
		success, err := handler.(relation.RelationService).CountFollowList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CountFollowListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCountFollowListArgs() interface{} {
	return &CountFollowListArgs{}
}

func newCountFollowListResult() interface{} {
	return &CountFollowListResult{}
}

type CountFollowListArgs struct {
	Req *relation.CountFollowListRequest
}

func (p *CountFollowListArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(relation.CountFollowListRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *CountFollowListArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *CountFollowListArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *CountFollowListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CountFollowListArgs) Unmarshal(in []byte) error {
	msg := new(relation.CountFollowListRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CountFollowListArgs_Req_DEFAULT *relation.CountFollowListRequest

func (p *CountFollowListArgs) GetReq() *relation.CountFollowListRequest {
	if !p.IsSetReq() {
		return CountFollowListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CountFollowListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CountFollowListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CountFollowListResult struct {
	Success *relation.CountFollowListResponse
}

var CountFollowListResult_Success_DEFAULT *relation.CountFollowListResponse

func (p *CountFollowListResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(relation.CountFollowListResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *CountFollowListResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *CountFollowListResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *CountFollowListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CountFollowListResult) Unmarshal(in []byte) error {
	msg := new(relation.CountFollowListResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CountFollowListResult) GetSuccess() *relation.CountFollowListResponse {
	if !p.IsSetSuccess() {
		return CountFollowListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CountFollowListResult) SetSuccess(x interface{}) {
	p.Success = x.(*relation.CountFollowListResponse)
}

func (p *CountFollowListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CountFollowListResult) GetResult() interface{} {
	return p.Success
}

func getFollowerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(relation.FollowerListRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(relation.RelationService).GetFollowerList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetFollowerListArgs:
		success, err := handler.(relation.RelationService).GetFollowerList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetFollowerListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetFollowerListArgs() interface{} {
	return &GetFollowerListArgs{}
}

func newGetFollowerListResult() interface{} {
	return &GetFollowerListResult{}
}

type GetFollowerListArgs struct {
	Req *relation.FollowerListRequest
}

func (p *GetFollowerListArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(relation.FollowerListRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetFollowerListArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetFollowerListArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetFollowerListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetFollowerListArgs) Unmarshal(in []byte) error {
	msg := new(relation.FollowerListRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetFollowerListArgs_Req_DEFAULT *relation.FollowerListRequest

func (p *GetFollowerListArgs) GetReq() *relation.FollowerListRequest {
	if !p.IsSetReq() {
		return GetFollowerListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetFollowerListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetFollowerListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetFollowerListResult struct {
	Success *relation.FollowerListResponse
}

var GetFollowerListResult_Success_DEFAULT *relation.FollowerListResponse

func (p *GetFollowerListResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(relation.FollowerListResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetFollowerListResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetFollowerListResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetFollowerListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetFollowerListResult) Unmarshal(in []byte) error {
	msg := new(relation.FollowerListResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetFollowerListResult) GetSuccess() *relation.FollowerListResponse {
	if !p.IsSetSuccess() {
		return GetFollowerListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetFollowerListResult) SetSuccess(x interface{}) {
	p.Success = x.(*relation.FollowerListResponse)
}

func (p *GetFollowerListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetFollowerListResult) GetResult() interface{} {
	return p.Success
}

func countFollowerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(relation.CountFollowerListRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(relation.RelationService).CountFollowerList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CountFollowerListArgs:
		success, err := handler.(relation.RelationService).CountFollowerList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CountFollowerListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCountFollowerListArgs() interface{} {
	return &CountFollowerListArgs{}
}

func newCountFollowerListResult() interface{} {
	return &CountFollowerListResult{}
}

type CountFollowerListArgs struct {
	Req *relation.CountFollowerListRequest
}

func (p *CountFollowerListArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(relation.CountFollowerListRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *CountFollowerListArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *CountFollowerListArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *CountFollowerListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CountFollowerListArgs) Unmarshal(in []byte) error {
	msg := new(relation.CountFollowerListRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CountFollowerListArgs_Req_DEFAULT *relation.CountFollowerListRequest

func (p *CountFollowerListArgs) GetReq() *relation.CountFollowerListRequest {
	if !p.IsSetReq() {
		return CountFollowerListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CountFollowerListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CountFollowerListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CountFollowerListResult struct {
	Success *relation.CountFollowerListResponse
}

var CountFollowerListResult_Success_DEFAULT *relation.CountFollowerListResponse

func (p *CountFollowerListResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(relation.CountFollowerListResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *CountFollowerListResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *CountFollowerListResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *CountFollowerListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CountFollowerListResult) Unmarshal(in []byte) error {
	msg := new(relation.CountFollowerListResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CountFollowerListResult) GetSuccess() *relation.CountFollowerListResponse {
	if !p.IsSetSuccess() {
		return CountFollowerListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CountFollowerListResult) SetSuccess(x interface{}) {
	p.Success = x.(*relation.CountFollowerListResponse)
}

func (p *CountFollowerListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CountFollowerListResult) GetResult() interface{} {
	return p.Success
}

func getFriendListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(relation.FriendListRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(relation.RelationService).GetFriendList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetFriendListArgs:
		success, err := handler.(relation.RelationService).GetFriendList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetFriendListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetFriendListArgs() interface{} {
	return &GetFriendListArgs{}
}

func newGetFriendListResult() interface{} {
	return &GetFriendListResult{}
}

type GetFriendListArgs struct {
	Req *relation.FriendListRequest
}

func (p *GetFriendListArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(relation.FriendListRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetFriendListArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetFriendListArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetFriendListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetFriendListArgs) Unmarshal(in []byte) error {
	msg := new(relation.FriendListRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetFriendListArgs_Req_DEFAULT *relation.FriendListRequest

func (p *GetFriendListArgs) GetReq() *relation.FriendListRequest {
	if !p.IsSetReq() {
		return GetFriendListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetFriendListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetFriendListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetFriendListResult struct {
	Success *relation.FriendListResponse
}

var GetFriendListResult_Success_DEFAULT *relation.FriendListResponse

func (p *GetFriendListResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(relation.FriendListResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetFriendListResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetFriendListResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetFriendListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetFriendListResult) Unmarshal(in []byte) error {
	msg := new(relation.FriendListResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetFriendListResult) GetSuccess() *relation.FriendListResponse {
	if !p.IsSetSuccess() {
		return GetFriendListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetFriendListResult) SetSuccess(x interface{}) {
	p.Success = x.(*relation.FriendListResponse)
}

func (p *GetFriendListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetFriendListResult) GetResult() interface{} {
	return p.Success
}

func isFollowHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(relation.IsFollowRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(relation.RelationService).IsFollow(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *IsFollowArgs:
		success, err := handler.(relation.RelationService).IsFollow(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*IsFollowResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newIsFollowArgs() interface{} {
	return &IsFollowArgs{}
}

func newIsFollowResult() interface{} {
	return &IsFollowResult{}
}

type IsFollowArgs struct {
	Req *relation.IsFollowRequest
}

func (p *IsFollowArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(relation.IsFollowRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *IsFollowArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *IsFollowArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *IsFollowArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *IsFollowArgs) Unmarshal(in []byte) error {
	msg := new(relation.IsFollowRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var IsFollowArgs_Req_DEFAULT *relation.IsFollowRequest

func (p *IsFollowArgs) GetReq() *relation.IsFollowRequest {
	if !p.IsSetReq() {
		return IsFollowArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *IsFollowArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *IsFollowArgs) GetFirstArgument() interface{} {
	return p.Req
}

type IsFollowResult struct {
	Success *relation.IsFollowResponse
}

var IsFollowResult_Success_DEFAULT *relation.IsFollowResponse

func (p *IsFollowResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(relation.IsFollowResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *IsFollowResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *IsFollowResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *IsFollowResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *IsFollowResult) Unmarshal(in []byte) error {
	msg := new(relation.IsFollowResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *IsFollowResult) GetSuccess() *relation.IsFollowResponse {
	if !p.IsSetSuccess() {
		return IsFollowResult_Success_DEFAULT
	}
	return p.Success
}

func (p *IsFollowResult) SetSuccess(x interface{}) {
	p.Success = x.(*relation.IsFollowResponse)
}

func (p *IsFollowResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *IsFollowResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Follow(ctx context.Context, Req *relation.RelationActionRequest) (r *relation.RelationActionResponse, err error) {
	var _args FollowArgs
	_args.Req = Req
	var _result FollowResult
	if err = p.c.Call(ctx, "Follow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Unfollow(ctx context.Context, Req *relation.RelationActionRequest) (r *relation.RelationActionResponse, err error) {
	var _args UnfollowArgs
	_args.Req = Req
	var _result UnfollowResult
	if err = p.c.Call(ctx, "Unfollow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFollowList(ctx context.Context, Req *relation.FollowListRequest) (r *relation.FollowListResponse, err error) {
	var _args GetFollowListArgs
	_args.Req = Req
	var _result GetFollowListResult
	if err = p.c.Call(ctx, "GetFollowList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CountFollowList(ctx context.Context, Req *relation.CountFollowListRequest) (r *relation.CountFollowListResponse, err error) {
	var _args CountFollowListArgs
	_args.Req = Req
	var _result CountFollowListResult
	if err = p.c.Call(ctx, "CountFollowList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFollowerList(ctx context.Context, Req *relation.FollowerListRequest) (r *relation.FollowerListResponse, err error) {
	var _args GetFollowerListArgs
	_args.Req = Req
	var _result GetFollowerListResult
	if err = p.c.Call(ctx, "GetFollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CountFollowerList(ctx context.Context, Req *relation.CountFollowerListRequest) (r *relation.CountFollowerListResponse, err error) {
	var _args CountFollowerListArgs
	_args.Req = Req
	var _result CountFollowerListResult
	if err = p.c.Call(ctx, "CountFollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFriendList(ctx context.Context, Req *relation.FriendListRequest) (r *relation.FriendListResponse, err error) {
	var _args GetFriendListArgs
	_args.Req = Req
	var _result GetFriendListResult
	if err = p.c.Call(ctx, "GetFriendList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IsFollow(ctx context.Context, Req *relation.IsFollowRequest) (r *relation.IsFollowResponse, err error) {
	var _args IsFollowArgs
	_args.Req = Req
	var _result IsFollowResult
	if err = p.c.Call(ctx, "IsFollow", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
